In [2]:
import pandas as pd
import numpy as np
import os

In [52]:
os.getcwd()
data = pd.read_csv("../Data/Analysis/close_pairs.csv")
data = data[data.columns[1:]]

In [53]:
coll = data[['Naam', 'District', 'Verkiezingdatum']]

#Empty columns
coll['InTKEK'] = ""
coll['Gevonden'] = ""
coll['Sterfdatum'] = ""
coll['Gebdatum'] = ""
coll['Sterfplaats'] = ""
coll['Vermogen'] = ""
coll['Link1'] = ""
coll['Link2'] = ""
coll['Polpartij'] = ""
coll['Opm'] = ""

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()
/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':
/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]

In [54]:
algevonden = ['B.A. Reigers', 'E.J.I. van Sonsbeek',
             'F.G. Mellink Pzn.', 'jhr.mr. H.B. van Tets',
             'H.P. Gelderman', 'J. Hoven',
             'J.H. Tromp Meesters', 'mr. S.J. baron van Pallandt',
             'W. Bos', 'G.A. Vos de Wael',
             'J.E. Stork', 'mr. A.A. van Bergen Ijzendoorn',
             'mr. H.A. Neeb', 'J. van der Breggen',
             'dr. T.C.L. Wijnmalen', 'mr. J.T. Buys',
             'mr. J.B.L. Wentholt', 'J.G. van Schaardenburg',
             'C.J. Vaillant', 'jhr.mr. H.G.C.L. Janssens',
             'mr. A.M. Maas Geesteranus']

In [85]:
coll['Gevonden'] = ['ja' if x in algevonden else '' for x in coll['Naam']]

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [89]:
coll.to_csv("../Administration/data_entry_file.csv", index=False)

## Part 2: Close pairs 2 and merge with existing Google Drive File

I try to get a more precise file, and merge it with the google drive file conditional on 'ja' and already identified as being non parliament, and then merge the two files.

In [35]:
data = pd.read_excel("../Data/data_entry_file_old.xlsx")

In [51]:
data = data[(data['InTKEK'] == 'nee') | (data['Gevonden'] == 'ja')]
data

,Naam,District,Verkiezingdatum,InTKEK,Gevonden,Sterfdatum,Gebdatum,Sterfplaats,Vermogen,Link1,Link2,Polpartij,Opm
19,mr. J. van Riemsdijk,Almelo,02/01/1849,nee,ja,01/11/1879,NaN,Almelo,NaN,https://www.genealogieonline.nl/en/genealogie-...,NaN,NaN,NaN
20,mr. H. van Sonsbeeck,Enschede,30/11/1848,nee,NaN,29/11/1865,NaN,Heino,NaN,NaN,NaN,NaN,NaN
21,mr. H. van Sonsbeeck,Enschede,16/12/1848,nee,NaN,29/11/1865,NaN,Heino,NaN,NaN,NaN,NaN,NaN
24,mr. R.W. Tadema,Zutphen,30/11/1848,nee,NaN,11/05/1860,NaN,Zutphen,NaN,NaN,NaN,NaN,NaN
28,J.G. Dolmans,Ysselstein,30/11/1848,nee,NaN,29/01/1856,NaN,NaN,NaN,https://www.genealogieonline.nl/en/stamboom-ro...,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1208,F.G. Mellink Pzn.,Amsterdam II,15/06/1897,NaN,ja,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1212,F.G. Mellink Pzn.,Amsterdam II,25/06/1897,NaN,ja,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1359,J. Hoven,Zwolle,25/06/1897,NaN,ja,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1493,C.A. Zelvelder,Alkmaar,31/03/1903,nee,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1585,J.H. Tromp Meesters,Steenwijk,16/06/1905,NaN,ja,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
# Now, full join with the column of new names in close_pairs2.csv

In [55]:
closepairs2 = pd.read_csv("../Administration/close_pairs2.csv")[['Naam', 'Verkiezingdatum', 'District']]

In [56]:
new_data_entry_file = data.merge(closepairs2, how='outer', on=['Naam','Verkiezingdatum', 'District'])

new_data_entry_file

,Naam,District,Verkiezingdatum,InTKEK,Gevonden,Sterfdatum,Gebdatum,Sterfplaats,Vermogen,Link1,Link2,Polpartij,Opm
0,mr. J. van Riemsdijk,Almelo,02/01/1849,nee,ja,01/11/1879,NaN,Almelo,NaN,https://www.genealogieonline.nl/en/genealogie-...,NaN,NaN,NaN
1,mr. H. van Sonsbeeck,Enschede,30/11/1848,nee,NaN,29/11/1865,NaN,Heino,NaN,NaN,NaN,NaN,NaN
2,mr. H. van Sonsbeeck,Enschede,16/12/1848,nee,NaN,29/11/1865,NaN,Heino,NaN,NaN,NaN,NaN,NaN
3,mr. R.W. Tadema,Zutphen,30/11/1848,nee,NaN,11/05/1860,NaN,Zutphen,NaN,NaN,NaN,NaN,NaN
4,J.G. Dolmans,Ysselstein,30/11/1848,nee,NaN,29/01/1856,NaN,NaN,NaN,https://www.genealogieonline.nl/en/stamboom-ro...,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
456,dr. Z. Kamerling,Amsterdam II,15/06/1917,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
457,dr. Z. Kamerling,Amsterdam II,22/06/1917,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
458,J. Schouten,Rotterdam II,14/12/1917,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
459,J. Schouten,Rotterdam II,21/12/1917,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
460,H.J. Versteeg,Schiedam,22/10/1907,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [57]:
new_data_entry_file['Naam'].drop_duplicates()
# 311 unique politicians

0      mr. J. van Riemsdijk
1      mr. H. van Sonsbeeck
3           mr. R.W. Tadema
4              J.G. Dolmans
5             W. de la Haye
               ...
447      T. van der Waerden
451             K. Stenhuis
452           G.J.H. Peters
456        dr. Z. Kamerling
458             J. Schouten
Name: Naam, Length: 311, dtype: object

In [58]:
new_data_entry_file.to_csv("../Administration/new_data_entry_file.csv")